apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: ldap_provider
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        id:
        - uid
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: "uid=ldapbinduser,ou=Users,o=60nkh1szatnktw9t5qfrmpt1,dc=jumpcloud,dc=com"
      bindPassword:
        name: ldap-secret
      ca:
        name: ldap-ca-config-map
      insecure: false
      url: "ldaps://ldap.jumpcloud.com:636/ou=Users,o=60nkh1szatnktw9t5qfrmpt1,dc=jumpcloud,dc=com"
